# Predicción de Abandono de Clientes en Telecomunicaciones

## Notebook 1 - Comprensión del Negocio y de los Datos

### Descripción del proyecto

El objetivo de este notebook es comprender el problema de negocio, cargar el conjunto de datos, analizar su estructura e identificar posibles problemas de calidad antes de comenzar el análisis exploratorio de datos (EDA).

Este notebook corresponde a la primera fase de la metodología **CRISP-DM**, centrada en la comprensión del negocio y de los datos.

---

## Desarrollo

In [1]:
import pandas as pd
import numpy as np

# Configuracion de visualizacion
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [2]:
df = pd.read_csv("../data/raw/telco.csv")

df.shape

(7043, 21)

In [3]:
df.columns.tolist()

['customerID',
 'gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'tenure',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'MonthlyCharges',
 'TotalCharges',
 'Churn']

In [4]:
# Diccionario de traducción

columnas = {
    "customerID": "ID_Cliente",
    "gender": "Genero",
    "SeniorCitizen": "Adulto_Mayor",
    "Partner": "Tiene_Pareja",
    "Dependents": "Tiene_Dependientes",
    "tenure": "Antiguedad_Meses",
    "PhoneService": "Servicio_Telefono",
    "MultipleLines": "Multiples_Lineas",
    "InternetService": "Servicio_Internet",
    "OnlineSecurity": "Seguridad_Online",
    "OnlineBackup": "Copia_Seguridad_Online",
    "DeviceProtection": "Proteccion_Dispositivo",
    "TechSupport": "Soporte_Tecnico",
    "StreamingTV": "Streaming_TV",
    "StreamingMovies": "Streaming_Peliculas",
    "Contract": "Tipo_Contrato",
    "PaperlessBilling": "Factura_Electronica",
    "PaymentMethod": "Metodo_Pago",
    "MonthlyCharges": "Cargo_Mensual",
    "TotalCharges": "Cargos_Totales",
    "Churn": "Abandono"
}

In [5]:
df.rename(columns=columnas, inplace=True)

In [6]:
df.columns.tolist()

['ID_Cliente',
 'Genero',
 'Adulto_Mayor',
 'Tiene_Pareja',
 'Tiene_Dependientes',
 'Antiguedad_Meses',
 'Servicio_Telefono',
 'Multiples_Lineas',
 'Servicio_Internet',
 'Seguridad_Online',
 'Copia_Seguridad_Online',
 'Proteccion_Dispositivo',
 'Soporte_Tecnico',
 'Streaming_TV',
 'Streaming_Peliculas',
 'Tipo_Contrato',
 'Factura_Electronica',
 'Metodo_Pago',
 'Cargo_Mensual',
 'Cargos_Totales',
 'Abandono']

| Variable               | Tipo              | Descripción                                     | Hipótesis de negocio                                                                     |
| ---------------------- | ----------------- | ----------------------------------------------- | ---------------------------------------------------------------------------------------- |
| ID_Cliente             | Identificador     | Identificador único del cliente.                | No aporta información predictiva. Se eliminará antes del modelado.                       |
| Genero                 | Categórica        | Género del cliente.                             | Puede influir ligeramente, aunque no se espera que sea determinante.                     |
| Adulto_Mayor           | Binaria           | Indica si el cliente es mayor de 65 años.       | Los clientes mayores podrían presentar un comportamiento diferente respecto al abandono. |
| Tiene_Pareja           | Binaria           | Indica si el cliente tiene pareja.              | Tener pareja puede aumentar la estabilidad del cliente.                                  |
| Tiene_Dependientes     | Binaria           | Indica si el cliente tiene personas a su cargo. | Los clientes con dependientes podrían cambiar menos de compañía.                         |
| Antiguedad_Meses       | Numérica          | Meses que el cliente lleva con la empresa.      | Es probable que los clientes nuevos abandonen con mayor frecuencia.                      |
| Servicio_Telefono      | Binaria           | Indica si dispone de servicio telefónico.       | Puede estar relacionado con el nivel de contratación del cliente.                        |
| Multiples_Lineas       | Categórica        | Cliente con varias líneas telefónicas.          | Los clientes con varios servicios podrían ser más fieles.                                |
| Servicio_Internet      | Categórica        | Tipo de servicio de Internet contratado.        | El tipo de conexión puede influir en la satisfacción del cliente.                        |
| Seguridad_Online       | Categórica        | Servicio de seguridad online contratado.        | Contratar servicios adicionales puede reducir el abandono.                               |
| Copia_Seguridad_Online | Categórica        | Servicio de copias de seguridad.                | Refleja mayor vinculación con la empresa.                                                |
| Proteccion_Dispositivo | Categórica        | Protección para los dispositivos del cliente.   | Puede indicar un cliente con mayor compromiso.                                           |
| Soporte_Tecnico        | Categórica        | Servicio de asistencia técnica.                 | Los clientes con soporte contratado podrían abandonar menos.                             |
| Streaming_TV           | Categórica        | Servicio de televisión en streaming.            | Más servicios contratados podrían aumentar la fidelidad.                                 |
| Streaming_Peliculas    | Categórica        | Servicio de películas en streaming.             | Igual que el anterior.                                                                   |
| Tipo_Contrato          | Categórica        | Tipo de contrato del cliente.                   | Los contratos mensuales suelen tener mayor tasa de abandono que los anuales.             |
| Factura_Electronica    | Binaria           | Uso de facturación electrónica.                 | Puede estar relacionada con el perfil digital del cliente.                               |
| Metodo_Pago            | Categórica        | Método de pago utilizado.                       | Algunos métodos de pago pueden asociarse a mayor abandono.                               |
| Cargo_Mensual          | Numérica          | Importe mensual que paga el cliente.            | Cuotas elevadas podrían aumentar el riesgo de abandono.                                  |
| Cargos_Totales         | Numérica          | Importe total pagado por el cliente.            | Está muy relacionado con la antigüedad del cliente.                                      |
| Abandono               | Variable objetivo | Indica si el cliente abandonó la compañía.      | Es la variable que queremos predecir.                                                    |

In [7]:
df

,ID_Cliente,Genero,Adulto_Mayor,Tiene_Pareja,Tiene_Dependientes,Antiguedad_Meses,Servicio_Telefono,Multiples_Lineas,Servicio_Internet,Seguridad_Online,Copia_Seguridad_Online,Proteccion_Dispositivo,Soporte_Tecnico,Streaming_TV,Streaming_Peliculas,Tipo_Contrato,Factura_Electronica,Metodo_Pago,Cargo_Mensual,Cargos_Totales,Abandono
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID_Cliente              7043 non-null   str
 1   Genero                  7043 non-null   str
 2   Adulto_Mayor            7043 non-null   int64
 3   Tiene_Pareja            7043 non-null   str
 4   Tiene_Dependientes      7043 non-null   str
 5   Antiguedad_Meses        7043 non-null   int64
 6   Servicio_Telefono       7043 non-null   str
 7   Multiples_Lineas        7043 non-null   str
 8   Servicio_Internet       7043 non-null   str
 9   Seguridad_Online        7043 non-null   str
 10  Copia_Seguridad_Online  7043 non-null   str
 11  Proteccion_Dispositivo  7043 non-null   str
 12  Soporte_Tecnico         7043 non-null   str
 13  Streaming_TV            7043 non-null   str
 14  Streaming_Peliculas     7043 non-null   str
 15  Tipo_Contrato           7043 non-null   str
 16  Factura_Electronica     7043 non-null   str
 17  Metodo_Pago             7043 non-null   str
 18  Cargo_Mensual           7043 non-null   float64
 19  Cargos_Totales          7043 non-null   str
 20  Abandono                7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [9]:
df["Cargos_Totales"].head(10)

0      29.85
1     1889.5
2     108.15
3    1840.75
4     151.65
5      820.5
6     1949.4
7      301.9
8    3046.05
9    3487.95
Name: Cargos_Totales, dtype: str

In [10]:
(df["Cargos_Totales"].str.strip() == "").sum()

np.int64(11)

In [11]:
df[df["Cargos_Totales"].str.strip() == ""][["Antiguedad_Meses", "Cargo_Mensual", "Cargos_Totales"]]

      Antiguedad_Meses  Cargo_Mensual Cargos_Totales
488                  0          52.55
753                  0          20.25
936                  0          80.85
1082                 0          25.75
1340                 0          56.05
3331                 0          19.85
3826                 0          25.35
4380                 0          20.00
5218                 0          19.70
6670                 0          73.35
6754                 0          61.90

## Decisión 1 - Columna Cargos_Totales

Se detectaron 11 registros con valores vacíos. Tras investigar, se comprobó que todos correspondían a clientes con Antiguedad_Meses = 0. Se concluye que estos clientes aún no habían generado cargos acumulados. Por tanto, los valores vacíos se sustituirán por 0 antes de convertir la columna a tipo numérico.

In [12]:
# Sustituir cadenas vacías por 0
df["Cargos_Totales"] = df["Cargos_Totales"].replace(" ", "0")

# Convertir la columna a tipo numérico
df["Cargos_Totales"] = pd.to_numeric(df["Cargos_Totales"])

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID_Cliente              7043 non-null   str
 1   Genero                  7043 non-null   str
 2   Adulto_Mayor            7043 non-null   int64
 3   Tiene_Pareja            7043 non-null   str
 4   Tiene_Dependientes      7043 non-null   str
 5   Antiguedad_Meses        7043 non-null   int64
 6   Servicio_Telefono       7043 non-null   str
 7   Multiples_Lineas        7043 non-null   str
 8   Servicio_Internet       7043 non-null   str
 9   Seguridad_Online        7043 non-null   str
 10  Copia_Seguridad_Online  7043 non-null   str
 11  Proteccion_Dispositivo  7043 non-null   str
 12  Soporte_Tecnico         7043 non-null   str
 13  Streaming_TV            7043 non-null   str
 14  Streaming_Peliculas     7043 non-null   str
 15  Tipo_Contrato           7043 non-null   str
 16  Factura_Electronica     7043 non-null   str
 17  Metodo_Pago             7043 non-null   str
 18  Cargo_Mensual           7043 non-null   float64
 19  Cargos_Totales          7043 non-null   float64
 20  Abandono                7043 non-null   str
dtypes: float64(2), int64(2), str(17)
memory usage: 1.1 MB

In [14]:
# Variables numéricas
variables_numericas = df.select_dtypes(include=["int64", "float64"]).columns.tolist()

variables_numericas

['Adulto_Mayor', 'Antiguedad_Meses', 'Cargo_Mensual', 'Cargos_Totales']

In [15]:
df.to_csv("../data/processed/telco_limpio.csv", index=False)

## Decisión 2 - Creación del conjunto de datos preparado

Tras completar la comprensión del conjunto de datos y realizar las primeras tareas de preparación (renombrado de columnas, corrección de tipos de datos y tratamiento de valores faltantes), se guarda una copia del dataset procesado.

Este archivo será el punto de partida de los siguientes notebooks, garantizando que todas las fases del proyecto trabajen sobre la misma versión del conjunto de datos.